UCSD-MASHED/chatapp

package.json

https://trello.com/c/yC7mE16l/2-ci-cd-pipeline
This PR extends ESLint to apply the recommended configuration.

Extend ESLint to use recommended config

---

.github/workflows/deploy_dev_to_beta.yml
.github/workflows/deploy_dev_to_beta_preview.yml
.github/workflows/deploy_main_to_prod.yml
.github/workflows/deploy_main_to_prod_preview.yml

https://trello.com/c/yC7mE16l/2-ci-cd-pipeline
This PR updates our workflows to run `npm run build` before running `npm test`.
The current ordering doesn't seem to be posing any problems, so this change is mainly to make the ordering more intuitive. (And perhaps this ordering *would* make a difference in certain circumstances, though I'm not sure).

Run npm test before npm run build in workflows

---

.github/workflows/jsdoc.yml
jsdoc.json
package-lock.json
package.json
src/modules/ChatMessage.js
src/modules/ChatRoom.js
src/modules/CreateUser.js
src/modules/Login.js
src/modules/User.js

https://trello.com/c/qMC31CWE/50-jsdocs-integration
Add jsdoc generation workflow.

Cz dy jsdoc integration

---

.github/workflows/jest_coverage.yml
package.json
src/__tests__/ChatRoom.test.js
src/modules/ChatRoom.js
src/modules/Login.js

https://trello.com/c/x8kxkoC5/53-code-coverage-in-jest
See ticket above.
Deployed here: https://ucsd-mashed.github.io/TaterTalkCoverage/

Add jest coverage generation and deployment

---

.github/workflows/jest_coverage.yml
package.json
src/__tests__/ChatRoom.test.js
src/modules/ChatRoom.js
src/modules/Login.js

https://trello.com/c/x8kxkoC5/53-code-coverage-in-jest
See ticket above.
Deployed here: https://ucsd-mashed.github.io/TaterTalkCoverage/

Add jest coverage generation and deployment (new)

---

src/__tests__/ChatRoom.test.js

https://trello.com/c/GIZ9sKqv/28-uc3-testing
This PR adds an integration test that mocks typing and sending a message. While it does not check that the database updates correctly, it checks that when a message is sent: (1) the proper data is given to the Firebase SDK functions and (2) the message form clears.

Add a test for sending a message

---

.eslintignore
.github/workflows/end_to_end_test.yml
.github/workflows/jest_coverage.yml
.github/workflows/jsdoc.yml
.github/workflows/linter.yml
.prettierignore
package.json
yarn.lock

N/A
Changed some workflow triggers so that only necessary workflow actions are triggered.

change some workflow triggers

---

cypress/fixtures/loginUser.json
cypress/fixtures/users.json
cypress/integration/login.spec.js
cypress/integration/user.spec.js
cypress/support/commands.js

https://trello.com/c/cM6N9VLN/49-cypress-end-to-end-testing
1. Added tests for user list and user search.
2. Improved login tests to cover more test cases.
See ticket above.

Add Cypress user lists/search and improved login tests

---

src/modules/ChatRoom.js
src/modules/User.js

https://trello.com/c/hyLm1GVH/56-ui-polishing
Performed minor UI changes, in particular:
- Added spacing between text field and send button
- Refactored User.js rendering to be able to add rounded corners on the list-group
- Removed unnecessary <></> tag from User.js
- Removed unnecessary property "share-btn" from log out button
None.

Minor UI changes + refactoring

---

.github/workflows/linter.yml
src/App.css
src/__tests__/ChatRoom.test.js
src/modules/ChatMessage.js
src/modules/ChatRoom.js

https://trello.com/c/hyLm1GVH/56-ui-polishing
See ticket

Add timestamp and tests

---

src/modules/ChatRoom.js

- [N/A] Did all the tests pass locally?
https://trello.com/c/EnDUgVp2/65-order-of-chat-switches-when-same-timestamp
See ticket above.

Fix message order inconsistent bug

---

src/modules/ChatRoom.js

- [N/A] Did all the tests pass locally?
N/A
Fix comment description.

comment fix

---

src/__tests__/ChatRoom.test.js
src/modules/ChatRoom.js
src/modules/CreateUser.js
src/modules/User.js

https://trello.com/c/BxpiGJdk/66-update-code-and-comments
See ticket.

Refactor code, fix comments

---

src/__tests__/UserLogin.test.js
src/modules/Login.js

https://trello.com/c/gAfOtGd0/76-change-tatertalk-to-tatertalks
Updated TaterTalk to TaterTalks

Update landing page

---

.github/workflows/test_coverage.yml
README.md
package.json

- [N/A] Did all the tests pass locally?
https://trello.com/c/PGGQdLDq/60-mvp-demo
Update code coverage status to code climate for badges and show

Upload test coverage status to code climate

---

src/App.css
src/modules/ChatRoom.js
src/modules/User.js

https://trello.com/c/ixx2tLRm/73-add-constrains-to-user-list
Hide sidebar when reducing the size of the window

User List Wrapper Scrollbar Style and Add min-width to User List

---

src/__tests__/ChatRoom.test.js
src/modules/LogOutButton.js

https://trello.com/c/NmPHy4Wx/75-ui-make-buttons-text-capitalization-consistent
Change "Log out" to "Log Out" to sync with "Sign In"

change Log out to Log Out

---

.github/workflows/test_coverage.yml
README.md
cypress.json
package.json

N/A
Add Jest and Cypress badge in readme

add jest and cypress badges

---

src/__tests__/UserLogin.test.js
src/modules/Login.js

Revert this ticket:
https://trello.com/c/gAfOtGd0/76-change-tatertalk-to-tatertalks
Changed LogIn screen name to TaterTalk and updated test

Revert app name to TaterTalk

---

cypress/integration/login.spec.js
src/modules/CreateUser.js

https://trello.com/c/EIzdaK5Y/91-username-input-validation
Add a username length limit of 20 characters.

Add username length limit

---

src/modules/Jokes.js
src/modules/Login.js

- [N/A ] Did you write tests for your code?
Just a simple renaming 

Renamed landing to jokes

---

src/modules/ChatMessage.js
src/modules/ChatRoom.js
src/modules/CreateUser.js
src/modules/LogOutButton.js
src/modules/Login.js
src/modules/User.js

https://trello.com/c/I0ePnKoV/96-add-header-to-all-functions-no-ctor-and-render
What does this PR contain?
This PR fills in missing function documentation and cleans up comments.
Please see my comments that I made in the changes below.

Add missing function documentation, clean up comments
